# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-29 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedfile',
            name='filename',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
    ]
