# Generated by Django 3.0.8 on 2020-10-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20190109_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedfile',
            name='aws_location',
            field=models.CharField(blank=True, default='', editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='relatedfile',
            name='store_as_filename',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
