# Generated by Django 3.0.8 on 2020-10-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20201001_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedfile',
            name='aws_location',
        ),
    ]
