# Generated by Django 3.2.16 on 2023-01-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_remove_relatedfile_aws_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedfile',
            name='oed_validated',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
