# Generated by Django 3.2.17 on 2023-02-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_relatedfile_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedfile',
            name='oed_validated',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
