# Generated by Django 3.2.19 on 2023-07-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_auto_20230731_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingfile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mappingfile',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
