# Generated by Django 3.2.19 on 2023-08-01 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_auto_20230731_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedfile',
            name='converted_filename',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='relatedfile',
            name='mapping_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapped_files', to='files.mappingfile'),
        ),
    ]
