# Generated by Django 3.2.19 on 2023-08-02 09:29

from django.db import migrations, models
import src.server.oasisapi.files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_auto_20230801_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingfile',
            name='input_validation_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=src.server.oasisapi.files.models.random_file_name),
        ),
        migrations.AddField(
            model_name='mappingfile',
            name='output_validation_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=src.server.oasisapi.files.models.random_file_name),
        ),
    ]
