# Generated by Django 3.2.19 on 2023-08-02 12:58

from django.db import migrations, models
import src.server.oasisapi.files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_relatedfile_conversion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedfile',
            name='conversion_log_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=src.server.oasisapi.files.models.random_file_name),
        ),
    ]
