# Generated by Django 3.2.19 on 2023-08-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('files', '0012_relatedfile_conversion_log_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingfile',
            name='groups',
            field=models.ManyToManyField(blank=True, default=None, help_text='Groups allowed to access this object', to='auth.Group'),
        ),
    ]
