# Generated by Django 3.2.19 on 2023-08-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_relatedfile_groups'),
        ('files', '0013_mappingfile_groups'),
    ]

    operations = [
    ]
