# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-04 14:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0002_auto_20190109_1715'),
        ('analysis_models', '0001_initial'),
        ('data_files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('filename', models.CharField(help_text='The name of the input file that will be used at runtime.', max_length=255)),
                ('file_description', models.CharField(help_text='Type of data contained within the file.', max_length=255)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_file', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_data_file', to='files.RelatedFile')),
                ('linked_models', models.ManyToManyField(blank=True, related_name='model_list', to='analysis_models.AnalysisModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='complexmodeldatafile',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='complexmodeldatafile',
            name='data_file',
        ),
        migrations.DeleteModel(
            name='ComplexModelDataFile',
        ),
    ]
