# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-05 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0002_auto_20190704_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='content_type',
            field=models.CharField(default='', help_text='File mime type', max_length=255),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='filename',
            field=models.CharField(help_text='Uploaded filename.', max_length=255),
        ),
    ]
