# Generated by Django 3.0.3 on 2020-11-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0005_auto_20190805_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='file_category',
            field=models.CharField(blank=True, default=None, help_text='Grouping label for data files (optional value)', max_length=255, null=True),
        ),
    ]
