# Generated by Django 3.2.20 on 2023-07-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('data_files', '0006_datafile_file_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafile',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='datafile',
            name='groups',
            field=models.ManyToManyField(blank=True, default=None, help_text='Groups allowed to access this object', to='auth.Group'),
        ),
    ]
