# Generated by Django 3.2.13 on 2022-06-21 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0007_datafile_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafile',
            options={'ordering': ['id']},
        ),
    ]
