FROM coreoasis/oasis_base:latest

RUN adduser --shell /bin/bash --disabled-password --gecos "" worker
WORKDIR /home/worker

# Install requirments
COPY ./requirements.in /tmp/
RUN pip install pip-tools
RUN pip-compile --output-file /tmp/requirements.txt /tmp/requirements.in
RUN pip install -r /tmp/requirements.txt

# Copy Static data
COPY ./data/static /var/oasis/model_data/OasisIM/1
COPY ./data/static /var/oasis/model_data/OasisIM/2

# Copy startup script + server config
COPY ./src/startup_worker.sh ./startup.sh
COPY ./conf.ini ./

COPY ./src/__init__.py ./src/
COPY ./src/common ./src/common/
COPY ./src/conf ./src/conf/
COPY ./src/model_execution_worker/ ./src/model_execution_worker/
COPY ./src/utils/ ./src/utils/
COPY ./tests /home/worker/tests

RUN mkdir -p /var/oasis/working && \
    mkdir -p /var/log/oasis && \
    touch /var/log/oasis/worker.log && \
    chmod 777 /var/log/oasis/worker.log

RUN chmod -R 777 /home/worker /var/log/oasis /var/oasis && \
    chown -R worker /home/worker && \
    chown -R worker /var/oasis && \
	chown -R worker /var/log && \
    chown -R worker /var/oasis/working

ENTRYPOINT ./startup.sh
