ARG KTOOLS_TAG=R_0_0_0_23

FROM coreoasis/ktools:$KTOOLS_TAG

RUN adduser --shell /bin/bash --disabled-password --gecos "" worker
WORKDIR /home/worker

COPY ./requirements.in /tmp/
RUN pip install pip-tools
RUN pip-compile --output-file /tmp/requirements.txt /tmp/requirements.in
RUN pip install -r /tmp/requirements.txt

COPY ./data/static /var/oasis/model_data/OasisIM/1
COPY ./data/static /var/oasis/model_data/OasisIM/2
COPY ./src/model_execution_worker/startup.sh ./
COPY ./src/common ./common/
COPY ./src/conf ./conf/
COPY ./src/model_execution_worker/ ./model_execution_worker/
COPY ./src/utils/ ./utils/
COPY ./tests /home/worker/tests

RUN mkdir -p /var/oasis/working && \
    mkdir -p /var/log/oasis && \
    touch /var/log/oasis/worker.log && \
    chmod 777 /var/log/oasis/worker.log

RUN chmod -R 777 /home/worker /var/log/oasis /var/oasis && \
    chown -R worker /home/worker && \
    chown -R worker /var/oasis && \
	chown -R worker /var/log && \
    chown -R worker /var/oasis/working

ENTRYPOINT ./startup.sh
