FROM ktools

RUN apt-get update
RUN apt-get install -y python-pip python-dev build-essential libmysqlclient-dev
RUN apt-get install -y vim iputils-ping

COPY ./src/model_execution_worker/requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt

RUN mkdir /var/log/oasis
RUN mkdir /var/oasis/working

RUN useradd -ms /bin/bash worker
RUN chown worker /var/log/oasis
RUN chown worker /var/oasis/working

USER worker
WORKDIR /home/worker

COPY ./src/model_execution_worker/startup.sh  ./

COPY ./src/common ./common/
COPY ./src/model_execution_worker/  ./model_execution_worker/
COPY ./src/model_execution/  ./model_execution/
COPY ./src/utils/ ./utils/

ENTRYPOINT ./utils/wait-for-it.sh rabbit:5672; ./utils/wait-for-it.sh mysql:3306; ./startup.sh; tail -f /dev/null
