FROM coreoasis/oasis_base:latest

RUN mkdir /var/log/oasis

RUN useradd -ms /bin/bash api
RUN chown api /var/log/oasis

COPY ./tests/ /home/api/tests/
COPY ./data/ /home/api/data/
COPY ./src/ /home/api/src/
COPY ./run_api_test_analysis.sh /home/api/

RUN chmod -R a+w /home/api/tests
RUN chmod -R a+w /home/api/data

USER api
WORKDIR /home/api

RUN mkdir upload
RUN mkdir download

ENTRYPOINT tail -f /dev/null
