FROM coreoasis/ktools:R_0_0_0_1

RUN apt-get update
RUN apt-get install -y python-pip python-dev build-essential libmysqlclient-dev python-flask unixodbc-dev
RUN apt-get install -y vim iputils-ping gdb

COPY ./src/model_execution_worker/requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt

COPY ./src/server/requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt

COPY ./src/oasis_utils/requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt

RUN mkdir /var/log/oasis

RUN useradd -ms /bin/bash oasis
RUN chown oasis /var/log/oasis

COPY ./src/common /home/oasis/src/common/
COPY ./src/model_execution/  /home/oasis/src/model_execution/
COPY ./src/utils/ /home/oasis/src/utils/
COPY ./src/oasis_utils/ /home/oasis/src/oasis_utils/
COPY ./src/server/ /home/oasis/src/server/
COPY ./data/ /home/oasis/data/
COPY ./tests/ /home/oasis/tests/
COPY ./run_test_analysis.sh /home/oasis/


#RUN chmod -R a+w /home/oasis/data
#RUN chmod -R a+w /home/oasis/tests
RUN chmod -R a+w /home/oasis

#USER oasis
#WORKDIR /home/oasis

#RUN python /home/oasis/tests/KparseTests.py 
RUN python /home/oasis/tests/ExposureTests.py 
