# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-08 10:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis_models', '0001_initial'),
        ('portfolios', '0001_initial'),
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='The name of the analysis', max_length=255)),
                ('status', models.CharField(choices=[('NEW', 'New'),
                                                     ('INPUTS_GENERATION_ERROR', 'Inputs generation error'),
                                                     ('INPUTS_GENERATION_CANCELLED', 'Inputs generation cancelled'),
                                                     ('INPUTS_GENERATION_STARTED', 'Inputs generation started'),
                                                     ('READY', 'Ready'),
                                                     ('RUN_STARTED', 'Run started'),
                                                     ('RUN_COMPLETED', 'Run completed'),
                                                     ('RUN_CANCELLED', 'Run cancelled'),
                                                     ('RUN_ERROR', 'Run error')],
                                            default='NEW', editable=False, max_length=27)),
                ('run_task_id', models.CharField(blank=True, default='', editable=False, max_length=255)),
                ('generate_inputs_task_id', models.CharField(blank=True, default='', editable=False, max_length=255)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
                ('input_errors_file', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_errors_file_analyses', to='files.RelatedFile')),
                ('input_file', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_file_analyses', to='files.RelatedFile')),
                ('input_generation_traceback_file', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_generation_traceback_analyses', to='files.RelatedFile')),
                ('model', models.ForeignKey(help_text='The model to link the analysis to', on_delete=django.db.models.deletion.DO_NOTHING, related_name='analyses', to='analysis_models.AnalysisModel')),
                ('output_file', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_file_analyses', to='files.RelatedFile')),
                ('portfolio', models.ForeignKey(help_text='The portfolio to link the analysis to', on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='portfolios.Portfolio')),
                ('run_traceback_file', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run_traceback_file_analyses', to='files.RelatedFile')),
                ('settings_file', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings_file_analyses', to='files.RelatedFile')),
            ],
            options={
                'verbose_name_plural': 'analyses',
            },
        ),
    ]
