# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='input_generation_traceback_file',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_generation_traceback_analyses', to='files.RelatedFile'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='run_traceback_file',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run_traceback_file_analyses', to='files.RelatedFile'),
        ),
    ]
