# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='complex_model_data_files',
            field=models.ManyToManyField(blank=True, related_name='complex_model_files_analyses', to='data_files.DataFile'),
        ),
    ]
