# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-25 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20190109_1715'),
        ('analyses', '0002_analysis_complex_model_data_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='input_errors_file',
        ),
        migrations.AddField(
            model_name='analysis',
            name='lookup_errors_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lookup_errors_file_analyses', to='files.RelatedFile'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='lookup_success_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lookup_success_file_analyses', to='files.RelatedFile'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='lookup_validation_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lookup_validation_file_analyses', to='files.RelatedFile'),
        ),
    ]
