# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_analysis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='task_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
    ]
