# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0003_analysis_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='status',
            field=models.CharField(choices=[('NOT_RAN', 'Not ran'), ('STARTED', 'Started'), ('STOPPED_COMPLETED', 'Stopped - Completed'), ('STOPPED_ERROR', 'Stopped - Error')], default='NOT_RAN', editable=False, max_length=17),
        ),
    ]
