# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-22 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20190109_1715'),
        ('analyses', '0004_analysis_complex_model_data_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='summary_levels_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_levels_file_analyses', to='files.RelatedFile'),
        ),
    ]
