# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-26 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0005_analysis_summary_levels_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='task_finished',
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='task_started',
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
    ]
