# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-15 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0006_auto_20190926_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='input_generation_traceback_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_generation_traceback_analyses', to='files.RelatedFile'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='run_traceback_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_traceback_file_analyses', to='files.RelatedFile'),
        ),
    ]
