# Generated by Django 2.2.8 on 2020-01-14 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20190109_1715'),
        ('analyses', '0007_auto_20191015_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='run_log_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_log_file_analyses', to='files.RelatedFile'),
        ),
    ]
