# Generated by Django 2.2.8 on 2020-01-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0008_analysis_run_log_file'),
        ('analyses', '0008_auto_20200107_1252'),
    ]

    operations = [
    ]
