# Generated by Django 3.0.3 on 2020-02-24 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_models', '0004_analysismodel_deleted'),
        ('analyses', '0009_merge_20200117_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='model',
            field=models.ForeignKey(help_text='The model to link the analysis to', on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analysis_models.AnalysisModel'),
        ),
    ]
