# Generated by Django 2.2.8 on 2020-01-28 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0009_merge_20200117_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=36, unique=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Run added to queue'), ('STARTED', 'Run started'), ('COMPLETED', 'Run completed'), ('CANCELLED', 'Run cancelled'), ('ERROR', 'Run error')], default='QUEUED', max_length=9)),
                ('queue_time', models.DateTimeField(default=None, null=True)),
                ('start_time', models.DateTimeField(default=None, null=True)),
                ('end_time', models.DateTimeField(default=None, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_task_statuses', to='analyses.Analysis')),
            ],
        ),
    ]
