# Generated by Django 2.2.8 on 2020-01-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0010_analysistaskstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistaskstatus',
            name='queue_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
