# Generated by Django 3.0.11 on 2021-03-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0010_auto_20200224_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('INPUTS_GENERATION_ERROR', 'Inputs generation error'), ('INPUTS_GENERATION_CANCEL_QUEUED', 'Inputs generation cancellation added to queue'), ('INPUTS_GENERATION_CANCELLED', 'Inputs generation cancelled'), ('INPUTS_GENERATION_STARTED', 'Inputs generation started'), ('INPUTS_GENERATION_QUEUED', 'Inputs generation added to queue'), ('READY', 'Ready'), ('RUN_QUEUED', 'Run added to queue'), ('RUN_STARTED', 'Run started'), ('RUN_COMPLETED', 'Run completed'), ('RUN_CANCEL_QUEUED', 'Run cancellation added to queue'), ('RUN_CANCELLED', 'Run cancelled'), ('RUN_ERROR', 'Run error')], default='NEW', editable=False, max_length=31),
        ),
    ]
