# Generated by Django 3.2.5 on 2021-09-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0011_auto_20210728_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='analysis_chunks',
            field=models.IntegerField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='lookup_chunks',
            field=models.IntegerField(blank=True, default=None, editable=False, null=True),
        ),
    ]
