# Generated by Django 3.2.20 on 2023-12-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0011_auto_20230724_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='run_mode',
            field=models.CharField(choices=[('V1', 'Single-Instance Execution'), ('V2', 'Distributed Execution')], default=None, editable=False, max_length=2, null=True),
        ),
    ]
