# Generated by Django 2.2.8 on 2020-01-29 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20190109_1715'),
        ('analyses', '0011_auto_20200128_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistaskstatus',
            name='error_log',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_run_status_error_logs', to='files.RelatedFile'),
        ),
        migrations.AddField(
            model_name='analysistaskstatus',
            name='output_log',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_run_status_output_logs', to='files.RelatedFile'),
        ),
    ]
