# Generated by Django 3.2.20 on 2024-01-12 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_models', '0008_analysismodel_run_mode'),
        ('analyses', '0012_analysis_run_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='chunking_options',
            field=models.OneToOneField(auto_created=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis_models.modelchunkingoptions'),
        ),
    ]
