# Generated by Django 3.2.5 on 2021-09-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0012_auto_20210928_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='sub_task_count',
            field=models.IntegerField(blank=True, default=None, editable=False, null=True),
        ),
    ]
