# Generated by Django 2.2.8 on 2020-02-05 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0012_auto_20200129_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistaskstatus',
            name='queue_name',
            field=models.CharField(default='-', editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysistaskstatus',
            name='analysis',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='sub_task_statuses', to='analyses.Analysis'),
        ),
        migrations.AlterField(
            model_name='analysistaskstatus',
            name='end_time',
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='analysistaskstatus',
            name='error_log',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_run_status_error_logs', to='files.RelatedFile'),
        ),
        migrations.AlterField(
            model_name='analysistaskstatus',
            name='output_log',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_run_status_output_logs', to='files.RelatedFile'),
        ),
        migrations.AlterField(
            model_name='analysistaskstatus',
            name='start_time',
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='analysistaskstatus',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Run added to queue'), ('STARTED', 'Run started'), ('COMPLETED', 'Run completed'), ('CANCELLED', 'Run cancelled'), ('ERROR', 'Run error')], default='QUEUED', editable=False, max_length=9),
        ),
        migrations.AlterField(
            model_name='analysistaskstatus',
            name='task_id',
            field=models.CharField(editable=False, max_length=36, unique=True),
        ),
    ]
