# Generated by Django 3.2.19 on 2024-02-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0012_analysis_raw_output_files'),
        ('analyses', '0013_analysis_chunking_options'),
    ]

    operations = [
    ]
