# Generated by Django 2.2.8 on 2020-02-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0013_auto_20200205_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistaskstatus',
            name='name',
            field=models.CharField(default='', editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysistaskstatus',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysistaskstatus',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Task waiting to be added to the queue'), ('QUEUED', 'Task added to queue'), ('STARTED', 'Task started'), ('COMPLETED', 'Task completed'), ('CANCELLED', 'Task cancelled'), ('ERROR', 'Task error')], default='PENDING', editable=False, max_length=9),
        ),
        migrations.AlterField(
            model_name='analysistaskstatus',
            name='task_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=36),
        ),
        migrations.AlterUniqueTogether(
            name='analysistaskstatus',
            unique_together={('analysis', 'slug')},
        ),
        migrations.AddConstraint(
            model_name='analysistaskstatus',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, task_id=''), fields=('task_id',), name='unique_task_id'),
        ),
    ]
