# Generated by Django 3.2.25 on 2025-01-15 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_merge_0006_relatedfile_groups_0013_mappingfile_groups'),
        ('analyses', '0015_auto_20241125_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistaskstatus',
            name='retry_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='analysistaskstatus',
            name='retry_log',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_run_status_retry_logs', to='files.relatedfile'),
        ),
    ]
