# Generated by Django 3.0.3 on 2020-03-09 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0010_auto_20200224_1213'),
        ('analyses', '0015_auto_20200227_1256'),
    ]

    operations = [
    ]
