# Generated by Django 3.2.25 on 2025-06-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0016_auto_20250115_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='run_tasks_complete',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='run_tasks_total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
