# Generated by Django 3.2.25 on 2025-07-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0016_auto_20250115_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='num_events_complete',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='num_events_total',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
