# Generated by Django 3.2.25 on 2025-04-17 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_merge_0006_relatedfile_groups_0013_mappingfile_groups'),
        ('analyses', '0016_auto_20250115_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistaskstatus',
            name='error_file',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_run_status_error_file', to='files.relatedfile'),
        ),
    ]
