# Generated by Django 5.2.8 on 2026-02-03 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0017_auto_20250730_1011'),
        ('analysis_models', '0010_auto_20241209_1632'),
        ('portfolios', '0010_portfolio_currency_conversion_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='model',
            field=models.ForeignKey(blank=True, help_text='The model to link the analysis to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analysis_models.analysismodel'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='portfolio',
            field=models.ForeignKey(blank=True, help_text='The portfolio to link the analysis to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='portfolios.portfolio'),
        ),
    ]
