# Generated by Django 3.2.5 on 2021-11-23 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0017_alter_analysis_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='priority',
            field=models.IntegerField(default=6, help_text='Priority of this analysis for input generation and execution. Set from 0 to 9 where 0 is the highest priority.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
