# Generated by Django 3.2.5 on 2021-11-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0014_remove_analysis_sub_task_count'),
        ('analyses', '0018_alter_analysis_priority'),
    ]

    operations = [
    ]
