# Generated by Django 5.2.11 on 2026-05-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0018_alter_analysis_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='raw_output_files',
        ),
    ]
