# Generated by Django 3.2.5 on 2021-12-02 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0019_merge_20211125_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='priority',
            field=models.IntegerField(default=4, help_text='Priority of this analysis for input generation and execution. Set from 1 to 10 where 10 is the highest priority.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
