# Generated by Django 3.2.19 on 2023-07-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_relatedfile_oed_validated'),
        ('analyses', '0021_auto_20220621_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='raw_output_files',
            field=models.ManyToManyField(blank=True, related_name='raw_output_files_analyses', to='files.RelatedFile'),
        ),
    ]
