# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 10:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_auto_20190109_1715'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexModelDataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file_name', models.CharField(help_text='The name of the complex model input file that will be used at runtime.', max_length=255)),
                ('file_description', models.CharField(help_text='Type of data contained within the file.', max_length=255)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complex_model_file', to=settings.AUTH_USER_MODEL)),
                ('data_file', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_file_complex_model_file', to='files.RelatedFile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
