# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 08:26
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import oasisapi.files.upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('accounts_file', models.FileField(default=None, null=True, upload_to=oasisapi.files.upload.random_file_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'json'])])),
                ('location_file', models.FileField(default=None, null=True, upload_to=oasisapi.files.upload.random_file_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'json'])])),
                ('reinsurance_source_file', models.FileField(default=None, null=True, upload_to=oasisapi.files.upload.random_file_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'json'])])),
                ('reinsurance_info_file', models.FileField(default=None, null=True, upload_to=oasisapi.files.upload.random_file_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'json'])])),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
