# Generated by Django 3.0.8 on 2020-08-25 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_auto_20190619_1226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioStatus',
        ),
    ]
