# Generated by Django 3.2.25 on 2025-03-13 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_merge_0006_relatedfile_groups_0013_mappingfile_groups'),
        ('portfolios', '0003_auto_20230724_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='exposure_run_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exposure_run_file_portfolios', to='files.relatedfile'),
        ),
    ]
