# Generated by Django 3.2.13 on 2022-06-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_portfolio_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['id']},
        ),
    ]
