# Generated by Django 3.2.25 on 2025-03-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_portfolio_exposure_run_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='exposure_status',
            field=models.CharField(choices=[('NONE', 'No exposure run calls'), ('INSUFFICIENT_DATA', 'Missing location/accounts file'), ('STARTED', 'An exposure run has been started'), ('ERROR', 'Exposure run has failed'), ('RUN_COMPLETED', 'Exposure run has successfully finished')], db_index=True, default='NONE', editable=False, max_length=17),
        ),
    ]
