# Generated by Django 3.2.25 on 2025-06-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_portfolio_exposure_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='validation_status',
            field=models.CharField(choices=[('NONE', 'No validation calls'), ('INSUFFICIENT_DATA', 'Missing input files'), ('STARTED', 'Validation has been started'), ('ERROR', 'Validation has failed'), ('RUN_COMPLETED', 'Validation has successfully finished')], db_index=True, default='NONE', editable=False, max_length=17),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='exposure_status',
            field=models.CharField(choices=[('NONE', 'No exposure run calls'), ('INSUFFICIENT_DATA', 'Missing input files'), ('STARTED', 'Exposure run has been started'), ('ERROR', 'Exposure run has failed'), ('RUN_COMPLETED', 'Exposure run has successfully finished')], db_index=True, default='NONE', editable=False, max_length=17),
        ),
    ]
