# Generated by Django 3.2.25 on 2025-06-06 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_merge_0006_relatedfile_groups_0013_mappingfile_groups'),
        ('portfolios', '0006_auto_20250602_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='exposure_transform_status',
            field=models.CharField(choices=[('NONE', 'No transformation calls'), ('INSUFFICIENT_DATA', 'Missing input files'), ('STARTED', 'Transformation has been started'), ('ERROR', 'Transformation has failed'), ('RUN_COMPLETED', 'Transformation has successfully finished')], db_index=True, default='NONE', editable=False, max_length=17),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='transform_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transform_file_portfolios', to='files.relatedfile'),
        ),
    ]
