# Generated by Django 3.2.25 on 2025-06-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_auto_20250602_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='exposure_transformation_status',
            field=models.CharField(choices=[('NONE', 'No transformation calls'), ('INSUFFICIENT_DATA', 'Missing input files'), ('STARTED', 'Transformation has been started'), ('ERROR', 'Transformation has failed'), ('RUN_COMPLETED', 'Transformation has successfully finished')], db_index=True, default='NONE', editable=False, max_length=17),
        ),
    ]
