# Generated by Django 3.2.25 on 2025-06-05 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_merge_0006_relatedfile_groups_0013_mappingfile_groups'),
        ('portfolios', '0007_portfolio_exposure_transformation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='exposure_transformation_status',
            new_name='exposure_transform_status',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='transform_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transform_file_portfolios', to='files.relatedfile'),
        ),
    ]
