# Generated by Django 3.2.25 on 2025-06-18 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_merge_0006_relatedfile_groups_0013_mappingfile_groups'),
        ('portfolios', '0007_auto_20250606_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='mapping_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapping_file_portfolios', to='files.relatedfile'),
        ),
    ]
