# Generated by Django 3.2.25 on 2025-07-16 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_merge_0006_relatedfile_groups_0013_mappingfile_groups'),
        ('portfolios', '0008_portfolio_mapping_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='run_errors_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errors_file_portfolios', to='files.relatedfile'),
        ),
    ]
