# Generated by Django 5.2.5 on 2025-12-16 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_merge_0006_relatedfile_groups_0013_mappingfile_groups'),
        ('portfolios', '0009_portfolio_run_errors_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='currency_conversion_json',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_conversion_json', to='files.relatedfile'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='reporting_currency',
            field=models.CharField(default='', editable=False, max_length=15),
        ),
    ]
