# Generated by Django 5.2.5 on 2026-01-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0010_portfolio_currency_conversion_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='reporting_currency',
            field=models.CharField(default='NONE', editable=False, max_length=15),
        ),
    ]
