FROM ubuntu:16.04

COPY ./apt.txt ./
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y $(grep -vE "^\s*#" apt.txt  | tr "\n" " ") && \
    rm -rf /var/lib/apt/lists/*

ARG BRANCH=master
RUN /bin/bash -c "pip install git+{https,ssh}://git@github.com/OasisLMF/OasisLMF.git@${BRANCH}#egg=oasislmf"
