api:
  dashboard: true

serversTransport:
  maxIdleConnsPerHost: 100
  forwardingTimeouts:
    dialTimeout: 300s
    idleConnTimeout: 5s

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: :443
    http:
      middlewares:
        - secureHeaders@file
      tls:
        certResolver: letsencrypt

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: dynamic.yml
    directory: "/etc/traefik/"

certificatesResolvers:
  letsencrypt:
    acme:
      # use your own vaild email address here
      email: ssl@firora.com
      storage: /letsencrypt/acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web
