{{- if eq .Values.ingress.tls.strategy "letsencrypt" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: {{ .Values.ingress.tls.server }}
    email: {{ .Values.ingress.tls.email }}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: traefik
            podTemplate:
              spec:
                nodeSelector:
                  "oasislmf/node-type": platform
{{- end }}
