apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.internalWorker.name }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "h.labels" . | nindent 4}} 
spec:
  replicas: {{ .Values.internalWorker.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.internalWorker.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "h.labels" . | nindent 8}}
        app: {{ .Values.internalWorker.name }}
    spec:
      containers:
        - name: {{ .Values.internalWorker.name }}
          image: {{ .Values.images.oasis.worker_internal.image }}:{{ .Values.images.oasis.worker_internal.version }}
          imagePullPolicy: {{ .Values.images.oasis.worker_internal.imagePullPolicy }}
          env:
            - name: OASIS_RUN_MODE
              value: server-internal
            {{- toYaml .Values.internalWorker.env | nindent 12 }}
            {{- include "h.celeryDbVars" . | indent 12}}
            {{- include "h.brokerVars" . | indent 12 }}
          startupProbe:
            exec:
              command: ["celery", "-A", "src.model_execution_worker.server_tasks", "inspect", "ping"]
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            exec:
              command: ["celery", "-A", "src.model_execution_worker.server_tasks", "inspect", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 60
            failureThreshold: 15
          volumeMounts:
            - name: shared-fs-persistent-storage
              mountPath: /shared-fs
      volumes:
{{- if ((.Values.volumes.host).sharedFs) }}
        - name: shared-fs-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.host.sharedFs.name }}
{{- else if ((.Values.volumes.azureFiles).sharedFs) }}
        - name: shared-fs-persistent-storage
{{- toYaml .Values.volumes.azureFiles.sharedFs | nindent 10 }}
{{- end }}
