{{- if .Values.internalWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.internalWorker.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.internalWorker.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.internalWorker.name }}
    spec:
      containers:
        - name: {{ .Values.internalWorker.name }}
          image: {{ .Values.internalWorker.image }}:{{ .Values.internalWorker.version }}
          imagePullPolicy: {{ .Values.internalWorker.imagePullPolicy }}
          env:
            {{- toYaml .Values.internalWorker.env | nindent 12 }}
          volumeMounts:
            - name: {{ .Values.internalWorker.volumeMounts.name }}
              mountPath: "{{ .Values.internalWorker.volumeMounts.mountPath }}"
            - name: {{ .Values.internalWorker.volumeMounts.name }}
              mountPath: /home/worker/model
      volumes:
        - name: {{ .Values.internalWorker.volumeMounts.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.internalWorker.volumes.persistentVolumeClaim.claimName }}
{{- end }}
