# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-08 10:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('supplier_id', models.CharField(help_text='The supplier ID for the model.', max_length=255)),
                ('model_id', models.CharField(help_text='The model ID for the model.', max_length=255)),
                ('version_id', models.CharField(help_text='The version ID for the model.', max_length=255)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resource_file', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_model_resource_file', to='files.RelatedFile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='analysismodel',
            unique_together=set([('supplier_id', 'model_id', 'version_id')]),
        ),
    ]
