# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysismodel',
            name='keys_server_uri',
        ),
    ]
