# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analysismodel',
            unique_together=set([('supplier_id', 'version_id')]),
        ),
    ]
