# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-08 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0004_remove_datafile_linked_models'),
        ('analysis_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysismodel',
            name='data_files',
            field=models.ManyToManyField(blank=True, related_name='analyses_model_data_files', to='data_files.DataFile'),
        ),
    ]
