# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-26 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('analysis_models', '0002_remove_analysismodel_keys_server_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysismodel',
            name='resources_file',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_resources_file', to='files.RelatedFile'),
        ),
    ]
