# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-13 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_models', '0002_analysismodel_data_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysismodel',
            name='ver_ktools',
            field=models.CharField(default=None, help_text='The worker ktools version.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysismodel',
            name='ver_oasislmf',
            field=models.CharField(default=None, help_text='The worker oasislmf version.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysismodel',
            name='ver_platform',
            field=models.CharField(default=None, help_text='The worker platform version.', max_length=255, null=True),
        ),
    ]
