# Generated by Django 3.0.3 on 2020-02-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_models', '0003_auto_20191213_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysismodel',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
