# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-26 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('analysis_models', '0003_analysismodel_resources_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysismodel',
            name='resources_file',
        ),
        migrations.AddField(
            model_name='analysismodel',
            name='resources',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_model_resources', to='files.RelatedFile'),
        ),
    ]
