# Generated by Django 2.2.8 on 2020-02-11 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_models', '0003_auto_20191213_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueModelAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_name', models.CharField(editable=False, max_length=255)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_associations', to='analysis_models.AnalysisModel')),
            ],
            options={
                'unique_together': {('model', 'queue_name')},
            },
        ),
    ]
