# Generated by Django 2.2.8 on 2020-02-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_models', '0004_queuemodelassociation'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysismodel',
            name='oasislmf_config',
            field=models.TextField(default=''),
        ),
    ]
