# Generated by Django 3.2.18 on 2023-03-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_models', '0005_auto_20220510_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysismodel',
            name='celery_tasks',
            field=models.JSONField(default=list, help_text='Celery tasks supported by worker', null=True),
        ),
    ]
