# Generated by Django 3.0.3 on 2020-03-09 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_models', '0005_analysismodel_oasislmf_config'),
        ('analysis_models', '0004_analysismodel_deleted'),
    ]

    operations = [
    ]
