# Generated by Django 3.2.5 on 2021-09-29 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_models', '0005_auto_20210728_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelChunkingOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('FIXED_CHUNKS', 'Fixed run partion sizes'), ('DYNAMIC_CHUNKS', 'Distribute runs based on input size')], default='FIXED_CHUNKS', max_length=14)),
                ('dynamic_locations_per_lookup', models.PositiveIntegerField(default=10000)),
                ('dynamic_events_per_analysis', models.PositiveIntegerField(default=1)),
                ('fixed_analysis_chunks', models.PositiveSmallIntegerField(default=1, null=True)),
                ('fixed_lookup_chunks', models.PositiveSmallIntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelScalingOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('FIXED_WORKERS', 'Fixed number of workers'), ('QUEUE_LOAD', 'Scale based on model queue load')], default='FIXED_WORKERS', max_length=13)),
                ('worker_count_fixed', models.PositiveSmallIntegerField(default=1)),
                ('worker_count_max', models.PositiveSmallIntegerField(default=10)),
                ('chunks_per_worker', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='analysismodel',
            name='num_analysis_chunks',
        ),
        migrations.AddField(
            model_name='analysismodel',
            name='chunking_options',
            field=models.OneToOneField(auto_created=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis_models.modelchunkingoptions'),
        ),
        migrations.AddField(
            model_name='analysismodel',
            name='scaling_options',
            field=models.OneToOneField(auto_created=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis_models.modelscalingoptions'),
        ),
    ]
