# Generated by Django 3.2.20 on 2023-07-24 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('analysis_models', '0005_auto_20220510_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelChunkingOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_strategy', models.CharField(choices=[('FIXED_CHUNKS', 'Fixed run partion sizes'), ('DYNAMIC_CHUNKS', 'Distribute runs based on input size')], default='FIXED_CHUNKS', max_length=14)),
                ('loss_strategy', models.CharField(choices=[('FIXED_CHUNKS', 'Fixed run partion sizes'), ('DYNAMIC_CHUNKS', 'Distribute runs based on input size')], default='FIXED_CHUNKS', max_length=14)),
                ('dynamic_locations_per_lookup', models.PositiveIntegerField(default=10000)),
                ('dynamic_events_per_analysis', models.PositiveIntegerField(default=1)),
                ('dynamic_chunks_max', models.PositiveIntegerField(default=200)),
                ('fixed_analysis_chunks', models.PositiveSmallIntegerField(default=1, null=True)),
                ('fixed_lookup_chunks', models.PositiveSmallIntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelScalingOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scaling_strategy', models.CharField(choices=[('FIXED_WORKERS', 'Fixed number of workers'), ('QUEUE_LOAD', 'Scale based on model queue load'), ('DYNAMIC_TASKS', 'Scale based on tasks per worker')], default='FIXED_WORKERS', max_length=13)),
                ('worker_count_fixed', models.PositiveSmallIntegerField(default=1)),
                ('worker_count_max', models.PositiveSmallIntegerField(default=10)),
                ('chunks_per_worker', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='analysismodel',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='analysismodel',
            name='groups',
            field=models.ManyToManyField(blank=True, default=None, help_text='Groups allowed to access this object', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='analysismodel',
            name='oasislmf_config',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='analysismodel',
            name='chunking_options',
            field=models.OneToOneField(auto_created=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis_models.modelchunkingoptions'),
        ),
        migrations.AddField(
            model_name='analysismodel',
            name='scaling_options',
            field=models.OneToOneField(auto_created=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis_models.modelscalingoptions'),
        ),
        migrations.CreateModel(
            name='QueueModelAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_name', models.CharField(editable=False, max_length=255)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_associations', to='analysis_models.analysismodel')),
            ],
            options={
                'unique_together': {('model', 'queue_name')},
            },
        ),
    ]
