# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-28 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_models', '0005_auto_20181126_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysismodel',
            name='creator_name',
            field=models.CharField(default=None, help_text='The username that added the model.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='analysismodel',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
