# Generated by Django 3.2.20 on 2023-09-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_models', '0006_auto_20230724_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelscalingoptions',
            name='worker_count_min',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
