# Generated by Django 3.2.5 on 2021-09-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_models', '0006_auto_20210929_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelchunkingoptions',
            old_name='strategy',
            new_name='lookup_strategy',
        ),
        migrations.RenameField(
            model_name='modelscalingoptions',
            old_name='strategy',
            new_name='scaling_strategy',
        ),
        migrations.AddField(
            model_name='modelchunkingoptions',
            name='loss_strategy',
            field=models.CharField(choices=[('FIXED_CHUNKS', 'Fixed run partion sizes'), ('DYNAMIC_CHUNKS', 'Distribute runs based on input size')], default='FIXED_CHUNKS', max_length=14),
        ),
    ]
