# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-28 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_models', '0006_auto_20181128_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysismodel',
            name='creator_name',
        ),
        migrations.AddField(
            model_name='analysismodel',
            name='owner',
            field=models.CharField(blank=True, default='', editable=False, help_text='The user who created this model.', max_length=255),
        ),
    ]
