# Generated by Django 3.0.3 on 2020-03-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_models', '0006_merge_20200309_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysismodel',
            name='num_analysis_chunks',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
