# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-28 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_models', '0007_auto_20181128_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysismodel',
            name='owner',
        ),
        migrations.AddField(
            model_name='analysismodel',
            name='creator_name',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
    ]
