# Generated by Django 3.2.5 on 2021-09-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_models', '0007_auto_20210930_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelscalingoptions',
            name='scaling_strategy',
            field=models.CharField(choices=[('FIXED_WORKERS', 'Fixed number of workers'), ('QUEUE_LOAD', 'Scale based on model queue load'), ('DYNAMIC_TASKS', 'Scale based on tasks per worker')], default='FIXED_WORKERS', max_length=13),
        ),
    ]
