# Generated by Django 3.2.20 on 2024-01-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_models', '0008_analysismodel_run_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysismodel',
            old_name='ver_ktools',
            new_name='v1_ver_ktools',
        ),
        migrations.RenameField(
            model_name='analysismodel',
            old_name='ver_oasislmf',
            new_name='v1_ver_oasislmf',
        ),
        migrations.RenameField(
            model_name='analysismodel',
            old_name='ver_platform',
            new_name='v1_ver_platform',
        ),
        migrations.AddField(
            model_name='analysismodel',
            name='v2_ver_ktools',
            field=models.CharField(default=None, help_text='V2 worker, ktools version.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysismodel',
            name='v2_ver_oasislmf',
            field=models.CharField(default=None, help_text='V2 worker, oasislmf version.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysismodel',
            name='v2_ver_platform',
            field=models.CharField(default=None, help_text='V2 worker, platform version.', max_length=255, null=True),
        ),
    ]
