# Generated by Django 3.2.13 on 2022-07-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_models', '0011_alter_analysismodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelchunkingoptions',
            name='dynamic_chunks_max',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
