#
# Celery Dockerfile
#
# https://github.com/dockerfile/celery
#

# Pull base image.
# FROM dockerfile/python
FROM python:2.7
RUN pip install celery
RUN pip install ConfigParser

# Define working directory.
#WORKDIR /home

# Define default command.
CMD ["bash"]
