FROM python:2.7

COPY ./requirements.txt ./
RUN pip install -r requirements.txt

RUN useradd -ms /bin/bash worker
USER worker
WORKDIR /home/worker

COPY ./CeleryConfig.py  ./
COPY ./Tasks.ini  ./
COPY ./tasks.py  ./
COPY ./TaskStatus.py  ./
COPY ./startup.sh  ./

ENTRYPOINT ./startup.sh;bash