CELERY_IMPORTS = ('tasks')
CELERY_IGNORE_RESULT = False
BROKER_URL = "rabbit" #IP address of the server running RabbitMQ and Celery
CELERY_RESULT_BACKEND = 'db+mysql://celery:password@mysql/celery'
CELERY_AMQP_TASK_RESULT_EXPIRES = 1000 
CELERY_TASK_SERIALIZER='json'
CELERY_RESULT_SERIALIZER='json'
CELERY_ACCEPT_CONTENT=['json']  # Ignore other content
CELERY_TIMEZONE='Europe/London'
CELERY_ENABLE_UTC=True