# --- Alternative method, allways run a build but with cache --------
#
#  Desc: cached build runs in 2-3mins but is probably not needed
#       https://github.com/docker/build-push-action
#       https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
#
#
#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v2
#
#    - name: Cache Docker layers
#      uses: actions/cache@v3
#      with:
#        path: /tmp/.buildx-cache
#        key: ${{ runner.os }}-buildx-${{ github.sha }}
#        restore-keys: |
#          ${{ runner.os }}-buildx-
#    - name: Create ktools-builder
#      uses: docker/build-push-action@v3
#      with:
#        push: false  # push image to remote reg
#        load: true   # load docker image as local image
#        context: .
#        tags: ktools-builder:latest
#        file: build/Dockerfile.clang-build
#        #outputs: type=docker,dest=/tmp/myimage.tar
#        cache-from: type=local,src=/tmp/.buildx-cache
#        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
#
#    # Temp fix
#    # https://github.com/docker/build-push-action/issues/252
#    # https://github.com/moby/buildkit/issues/1896
#    - name: Move cache
#      run: |
#        rm -rf /tmp/.buildx-cache
#        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
# ----------------------------------------------------------------
#    - name: Build with Autotools
#      uses: addnab/docker-run-action@v3
#      with:
#        image: ktools-builder:latest
#        #shell: bash
#        run: ./build-autotools.sh
#        #options: -v ${{ github.workspace }}:/var/ktools
#
#    - name: Build with Cmake
#      uses: addnab/docker-run-action@v3
#      with:
#        image: ktools-builder:latest
#        #shell: bash
#        options: -v ${{ github.workspace }}:/var/ktools
#        run: ./build-cmake.sh
  
