name: CI
on:
  pull_request:
jobs:
  minikube:
    runs-on: ubuntu-latest
    env:
      OASIS_MODEL_DATA_DIR: /shared-fs/PIWIND
    steps:
      - name: Clone OasisPiWind model data
        run: |
          git clone https://github.com/OasisLMF/OasisPiWind.git /tmp/piwind

      - name: Set OASIS_MODEL_DATA_DIR env
        run: echo "OASIS_MODEL_DATA_DIR=/tmp/piwind" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      - name: Build Docker images
        run: |
          eval $(minikube docker-env)
          
          docker build -f Dockerfile.api_server -t coreoasis/api_server:dev .
          docker build -f Dockerfile.model_worker -t coreoasis/model_worker:dev .

          pushd kubernetes/worker-controller
              docker build -t coreoasis/worker_controller:dev .
          popd

      - name: Upload PiWind model data
        run: |
          ./kubernetes/scripts/k8s/upload_piwind_model_data.sh $OASIS_MODEL_DATA_DIR

      - name: Deploy Platform
        run: |
          if ! helm status platform > /dev/null 2>&1; then
              helm install platform oasis-platform
          else
              helm upgrade platform oasis-platform
          fi
        working-directory: kubernetes/charts

      - name: Deploy Models
        run: |
          if ! helm status models > /dev/null 2>&1; then
              helm install models oasis-models
          else
              helm upgrade models oasis-models
          fi
        working-directory: kubernetes/charts

      - name: Checkout PiWind
        uses: actions/checkout@v3
        with:
          repository: OasisLMF/OasisPiWind
          ref: main

      - name: Authenticate
        id: auth
        run: |
          TOKEN=$(curl -s -X POST "${{ secrets.OIDC_ENDPOINT }}/protocol/openid-connect/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=password" \
            -d "client_id=${{ secrets.OIDC_CLIENT_ID }}" \
            -d "client_secret=${{ secrets.OIDC_CLIENT_SECRET }}" \
            -d "username=${{ secrets.OIDC_USERNAME }}" \
            -d "password=${{ secrets.OIDC_PASSWORD }}" | jq -r '.access_token')

          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Create Portfolio
        run: |
          PORTFOLIO_ID=$(curl -s -X POST https://ui.oasis.local/api/v1/portfolios/ \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"name": "PiWind Portfolio"}' | jq -r '.id')

          echo "PORTFOLIO_ID=$PORTFOLIO_ID" >> $GITHUB_ENV

      - name: Upload Locations File
        run: |
          curl -s -X POST https://ui.oasis.local/api/v1/portfolios/$PORTFOLIO_ID/locations_file/ \
            -H "Authorization: Bearer $TOKEN" \
            -F "file=@tests/inputs/SourceLocOEDPiWind10.csv"

      - name: Create Model
        run: |
          MODEL_ID=$(curl -s -X POST https://ui.oasis.local/api/v1/models/ \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"name": "piwind", "version": "1.0"}' | jq -r '.id')

          echo "MODEL_ID=$MODEL_ID" >> $GITHUB_ENV

      - name: Create Analysis
        run: |
          ANALYSIS_ID=$(curl -s -X POST https://ui.oasis.local/api/v1/portfolios/$PORTFOLIO_ID/create_analysis/ \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"model\": $MODEL_ID}" | jq -r '.id')

          echo "ANALYSIS_ID=$ANALYSIS_ID" >> $GITHUB_ENV

      - name: Upload Analysis Settings
        run: |
          curl -s -X POST https://ui.oasis.local/api/v1/analyses/$ANALYSIS_ID/analysis_settings/ \
            -H "Authorization: Bearer $TOKEN" \
            -F "file=@analysis_settings.json"

      - name: Run Analysis
        run: |
          curl -s -X POST https://ui.oasis.local/api/v1/analyses/$ANALYSIS_ID/run/ \
            -H "Authorization: Bearer $TOKEN"